const SHORT_MOVIE_DURATION = 40;
const MOVIES_TO_SHOW_XL = 16;
const MOVIES_TO_SHOW_L = 12;
const MOVIES_TO_SHOW_M = 8;
const MOVIES_TO_SHOW_S = 5;
const MOVIES_TO_ADD_L = 4;
const MOVIES_TO_ADD_M = 3;
const MOVIES_TO_ADD_S = 2;
const WINDOW_WIDTH_L = 1160;
const WINDOW_WIDTH_M = 910;
const WINDOW_WIDTH_S = 728;

module.exports = {
  SHORT_MOVIE_DURATION,
  MOVIES_TO_SHOW_XL,
  MOVIES_TO_SHOW_L,
  MOVIES_TO_SHOW_M,
  MOVIES_TO_SHOW_S,
  MOVIES_TO_ADD_L,
  MOVIES_TO_ADD_M,
  MOVIES_TO_ADD_S,
  WINDOW_WIDTH_L,
  WINDOW_WIDTH_M,
  WINDOW_WIDTH_S
}
